### ISSUE TITLE
Acentuação

### ISSUE THREAD

**Issue by victjar** [olegon/fatec-es3-stop#4]
Deve-se desconsiderar palavras iguais com diferença de acento.

**Comment by olegon** [comment]
Acabei usando o seguinte processo:

1. Trocar ocorrências de `áàãâä` por `a`;
1. Trocar ocorrências de `áàãâä` por `a`;
1. Trocar ocorrências de `áàãâä` por `a`;
1. Trocar ocorrências de `áàãâä` por `a`;
